config/routes.rb
Rails.application.routes.draw do
  resources :liquors
  get 'category/liquor', to: 'liquors#index', as: 'category_liquors'

  resources :freshfoods, path: 'category/freshfoods' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :householdproducts, path: 'category/householdproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :vegesproducts, path: 'category/vegesproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :babyproducts, path: 'category/babyproducts' do
    resources :products, only: [:show], controller: 'products'
  end 
  
  resources :cosmeticsproducts, path: 'category/cosmeticsproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :bevaragesproducts, path: 'category/bevaragesproducts' do
    resources :products, only: [:show], controller: 'products'
  end

  resources :products, only: [:index, :show]

  get '/categories_with_products/:category_name', to: 'products#categories_with_products'
  get '/categories_with_products/:category_name/:product_id', to: 'products#categories_with_products'


  

  get '/category/:category_name/:product_id', to: 'products#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/householdproduct.rb
class Householdproduct < ApplicationRecord
end

app/controllers/householdproducts_controller.rb
class HouseholdproductsController < ApplicationController
  before_action :set_householdproduct, only: %i[ show edit update destroy ]

  # GET /householdproducts or /householdproducts.json
  def index
    @householdproducts = Householdproduct.all
  end

  # GET /householdproducts/1 or /householdproducts/1.json
  def show
  end

  # GET /householdproducts/new
  def new
    @householdproduct = Householdproduct.new
  end

  # GET /householdproducts/1/edit
  def edit
  end

  # POST /householdproducts or /householdproducts.json
  def create
    @householdproduct = Householdproduct.new(householdproduct_params)

    respond_to do |format|
      if @householdproduct.save
        format.html { redirect_to householdproduct_url(@householdproduct), notice: "Householdproduct was successfully created." }
        format.json { render :show, status: :created, location: @householdproduct }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @householdproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /householdproducts/1 or /householdproducts/1.json
  def update
    respond_to do |format|
      if @householdproduct.update(householdproduct_params)
        format.html { redirect_to householdproduct_url(@householdproduct), notice: "Householdproduct was successfully updated." }
        format.json { render :show, status: :ok, location: @householdproduct }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @householdproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /householdproducts/1 or /householdproducts/1.json
  def destroy
    @householdproduct.destroy

    respond_to do |format|
      format.html { redirect_to householdproducts_url, notice: "Householdproduct was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_householdproduct
      @householdproduct = Householdproduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def householdproduct_params
      params.require(:householdproduct).permit(:name, :image, :price, :category)
    end
end

app/helpers/householdproducts_helper.rb
module HouseholdproductsHelper
end

app/views/householdproducts/_form.html.erb
<%= form_with(model: householdproduct) do |form| %>
  <% if householdproduct.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(householdproduct.errors.count, "error") %> prohibited this householdproduct from being saved:</h2>

      <ul>
        <% householdproduct.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/householdproducts/_householdproduct.html.erb
<div id="<%= dom_id householdproduct %>">
  <p>
    <strong>Name:</strong>
    <%= householdproduct.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= householdproduct.image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= householdproduct.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= householdproduct.category %>
  </p>

</div>

app/views/householdproducts/edit.html.erb
<h1>Editing householdproduct</h1>

<%= render "form", householdproduct: @householdproduct %>

<br>

<div>
  <%= link_to "Show this householdproduct", @householdproduct %> |
  <%= link_to "Back to householdproducts", householdproducts_path %>
</div>

app/views/householdproducts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Householdproducts</h1>

<div id="householdproducts">
  <% @householdproducts.each do |householdproduct| %>
    <%= render householdproduct %>
    <p>
      <%= link_to "Show this householdproduct", householdproduct %>
    </p>
  <% end %>
</div>

<%= link_to "New householdproduct", new_householdproduct_path %>

app/views/householdproducts/new.html.erb
<h1>New householdproduct</h1>

<%= render "form", householdproduct: @householdproduct %>

<br>

<div>
  <%= link_to "Back to householdproducts", householdproducts_path %>
</div>

app/views/householdproducts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @householdproduct %>

<div>
  <%= link_to "Edit this householdproduct", edit_householdproduct_path(@householdproduct) %> |
  <%= link_to "Back to householdproducts", householdproducts_path %>

  <%= button_to "Destroy this householdproduct", @householdproduct, method: :delete %>
</div>