config/routes.rb
Rails.application.routes.draw do
  resources :liquors
  get 'category/liquor', to: 'liquors#index', as: 'category_liquors'

  resources :freshfoods, path: 'category/freshfoods' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :householdproducts, path: 'category/householdproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :vegesproducts, path: 'category/vegesproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :babyproducts, path: 'category/babyproducts' do
    resources :products, only: [:show], controller: 'products'
  end 
  
  resources :cosmeticsproducts, path: 'category/cosmeticsproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :bevaragesproducts, path: 'category/bevaragesproducts' do
    resources :products, only: [:show], controller: 'products'
  end

  resources :products, only: [:index, :show]

  get '/categories_with_products/:category_name', to: 'products#categories_with_products'
  get '/categories_with_products/:category_name/:product_id', to: 'products#categories_with_products'


  

  get '/category/:category_name/:product_id', to: 'products#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/vegesproduct.rb
class Vegesproduct < ApplicationRecord
end

app/controllers/vegesproducts_controller.rb
class VegesproductsController < ApplicationController
  before_action :set_vegesproduct, only: %i[ show edit update destroy ]

  # GET /vegesproducts or /vegesproducts.json
  def index
    @vegesproducts = Vegesproduct.all
    render json: @vegesproducts, only: [:id, :name, :image, :price], methods: [:category]

  end

  # GET /vegesproducts/1 or /vegesproducts/1.json
  def show
  end

  # GET /vegesproducts/new
  def new
    @vegesproduct = Vegesproduct.new
    render json: @vegesproducts, only: [:id, :name, :image, :price], methods: [:category]

  end

  # GET /vegesproducts/1/edit
  def edit
  end

  # POST /vegesproducts or /vegesproducts.json
  def create
    @vegesproduct = Vegesproduct.new(vegesproduct_params)

    respond_to do |format|
      if @vegesproduct.save
        format.html { redirect_to vegesproduct_url(@vegesproduct), notice: "Vegesproduct was successfully created." }
        format.json { render :show, status: :created, location: @vegesproduct }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vegesproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vegesproducts/1 or /vegesproducts/1.json
  def update
    respond_to do |format|
      if @vegesproduct.update(vegesproduct_params)
        format.html { redirect_to vegesproduct_url(@vegesproduct), notice: "Vegesproduct was successfully updated." }
        format.json { render :show, status: :ok, location: @vegesproduct }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vegesproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vegesproducts/1 or /vegesproducts/1.json
  def destroy
    @vegesproduct.destroy

    respond_to do |format|
      format.html { redirect_to vegesproducts_url, notice: "Vegesproduct was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vegesproduct
      @vegesproduct = Vegesproduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vegesproduct_params
      params.require(:vegesproduct).permit(:name, :image, :price, :category)
    end
end

app/helpers/vegesproducts_helper.rb
module VegesproductsHelper
end

app/views/vegesproducts/_form.html.erb
<%= form_with(model: vegesproduct) do |form| %>
  <% if vegesproduct.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vegesproduct.errors.count, "error") %> prohibited this vegesproduct from being saved:</h2>

      <ul>
        <% vegesproduct.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vegesproducts/_vegesproduct.html.erb
<div id="<%= dom_id vegesproduct %>">
  <p>
    <strong>Name:</strong>
    <%= vegesproduct.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= vegesproduct.image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= vegesproduct.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= vegesproduct.category %>
  </p>

</div>

app/views/vegesproducts/edit.html.erb
<h1>Editing vegesproduct</h1>

<%= render "form", vegesproduct: @vegesproduct %>

<br>

<div>
  <%= link_to "Show this vegesproduct", @vegesproduct %> |
  <%= link_to "Back to vegesproducts", vegesproducts_path %>
</div>

app/views/vegesproducts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vegesproducts</h1>

<div id="vegesproducts">
  <% @vegesproducts.each do |vegesproduct| %>
    <%= render vegesproduct %>
    <p>
      <%= link_to "Show this vegesproduct", vegesproduct %>
    </p>
  <% end %>
</div>

<%= link_to "New vegesproduct", new_vegesproduct_path %>

app/views/vegesproducts/new.html.erb
<h1>New vegesproduct</h1>

<%= render "form", vegesproduct: @vegesproduct %>

<br>

<div>
  <%= link_to "Back to vegesproducts", vegesproducts_path %>
</div>

app/views/vegesproducts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vegesproduct %>

<div>
  <%= link_to "Edit this vegesproduct", edit_vegesproduct_path(@vegesproduct) %> |
  <%= link_to "Back to vegesproducts", vegesproducts_path %>

  <%= button_to "Destroy this vegesproduct", @vegesproduct, method: :delete %>
</div>