config/routes.rb
Rails.application.routes.draw do
  resources :liquors
  get 'category/liquor', to: 'liquors#index', as: 'category_liquors'

  resources :freshfoods, path: 'category/freshfoods' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :householdproducts, path: 'category/householdproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :vegesproducts, path: 'category/vegesproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :babyproducts, path: 'category/babyproducts' do
    resources :products, only: [:show], controller: 'products'
  end 
  
  resources :cosmeticsproducts, path: 'category/cosmeticsproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :bevaragesproducts, path: 'category/bevaragesproducts' do
    resources :products, only: [:show], controller: 'products'
  end

  resources :products, only: [:index, :show]

  get '/categories_with_products/:category_name', to: 'products#categories_with_products'
  get '/categories_with_products/:category_name/:product_id', to: 'products#categories_with_products'


  

  get '/category/:category_name/:product_id', to: 'products#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/babyproduct.rb
class Babyproduct < ApplicationRecord
end

app/controllers/babyproducts_controller.rb
class BabyproductsController < ApplicationController
  before_action :set_babyproduct, only: %i[ show edit update destroy ]

  # GET /babyproducts or /babyproducts.json
  def index
    @babyproducts = Babyproduct.all
  end

  # GET /babyproducts/1 or /babyproducts/1.json
  def show
  end

  # GET /babyproducts/new
  def new
    @babyproduct = Babyproduct.new
  end

  # GET /babyproducts/1/edit
  def edit
  end

  # POST /babyproducts or /babyproducts.json
  def create
    @babyproduct = Babyproduct.new(babyproduct_params)

    respond_to do |format|
      if @babyproduct.save
        format.html { redirect_to babyproduct_url(@babyproduct), notice: "Babyproduct was successfully created." }
        format.json { render :show, status: :created, location: @babyproduct }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @babyproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babyproducts/1 or /babyproducts/1.json
  def update
    respond_to do |format|
      if @babyproduct.update(babyproduct_params)
        format.html { redirect_to babyproduct_url(@babyproduct), notice: "Babyproduct was successfully updated." }
        format.json { render :show, status: :ok, location: @babyproduct }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @babyproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babyproducts/1 or /babyproducts/1.json
  def destroy
    @babyproduct.destroy

    respond_to do |format|
      format.html { redirect_to babyproducts_url, notice: "Babyproduct was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_babyproduct
      @babyproduct = Babyproduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def babyproduct_params
      params.require(:babyproduct).permit(:name, :image, :price, :category)
    end
end

app/helpers/babyproducts_helper.rb
module BabyproductsHelper
end

app/views/babyproducts/_babyproduct.html.erb
<div id="<%= dom_id babyproduct %>">
  <p>
    <strong>Name:</strong>
    <%= babyproduct.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= babyproduct.image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= babyproduct.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= babyproduct.category %>
  </p>

</div>

app/views/babyproducts/_form.html.erb
<%= form_with(model: babyproduct) do |form| %>
  <% if babyproduct.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(babyproduct.errors.count, "error") %> prohibited this babyproduct from being saved:</h2>

      <ul>
        <% babyproduct.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/babyproducts/edit.html.erb
<h1>Editing babyproduct</h1>

<%= render "form", babyproduct: @babyproduct %>

<br>

<div>
  <%= link_to "Show this babyproduct", @babyproduct %> |
  <%= link_to "Back to babyproducts", babyproducts_path %>
</div>

app/views/babyproducts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Babyproducts</h1>

<div id="babyproducts">
  <% @babyproducts.each do |babyproduct| %>
    <%= render babyproduct %>
    <p>
      <%= link_to "Show this babyproduct", babyproduct %>
    </p>
  <% end %>
</div>

<%= link_to "New babyproduct", new_babyproduct_path %>

app/views/babyproducts/new.html.erb
<h1>New babyproduct</h1>

<%= render "form", babyproduct: @babyproduct %>

<br>

<div>
  <%= link_to "Back to babyproducts", babyproducts_path %>
</div>

app/views/babyproducts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @babyproduct %>

<div>
  <%= link_to "Edit this babyproduct", edit_babyproduct_path(@babyproduct) %> |
  <%= link_to "Back to babyproducts", babyproducts_path %>

  <%= button_to "Destroy this babyproduct", @babyproduct, method: :delete %>
</div>