config/routes.rb
Rails.application.routes.draw do
  resources :liquors
  get 'category/liquor', to: 'liquors#index', as: 'category_liquors'

  resources :freshfoods, path: 'category/freshfoods' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :householdproducts, path: 'category/householdproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :vegesproducts, path: 'category/vegesproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :babyproducts, path: 'category/babyproducts' do
    resources :products, only: [:show], controller: 'products'
  end 
  
  resources :cosmeticsproducts, path: 'category/cosmeticsproducts' do
    resources :products, only: [:show], controller: 'products'
  end
  
  resources :bevaragesproducts, path: 'category/bevaragesproducts' do
    resources :products, only: [:show], controller: 'products'
  end

  resources :products, only: [:index, :show]

  get '/categories_with_products/:category_name', to: 'products#categories_with_products'
  get '/categories_with_products/:category_name/:product_id', to: 'products#categories_with_products'


  

  get '/category/:category_name/:product_id', to: 'products#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cosmeticsproduct.rb
class Cosmeticsproduct < ApplicationRecord
end

app/controllers/cosmeticsproducts_controller.rb
class CosmeticsproductsController < ApplicationController
  before_action :set_cosmeticsproduct, only: %i[ show edit update destroy ]

  # GET /cosmeticsproducts or /cosmeticsproducts.json
  def index
    @cosmeticsproducts = Cosmeticsproduct.all
  end

  # GET /cosmeticsproducts/1 or /cosmeticsproducts/1.json
  def show
  end

  # GET /cosmeticsproducts/new
  def new
    @cosmeticsproduct = Cosmeticsproduct.new
  end

  # GET /cosmeticsproducts/1/edit
  def edit
  end

  # POST /cosmeticsproducts or /cosmeticsproducts.json
  def create
    @cosmeticsproduct = Cosmeticsproduct.new(cosmeticsproduct_params)

    respond_to do |format|
      if @cosmeticsproduct.save
        format.html { redirect_to cosmeticsproduct_url(@cosmeticsproduct), notice: "Cosmeticsproduct was successfully created." }
        format.json { render :show, status: :created, location: @cosmeticsproduct }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cosmeticsproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cosmeticsproducts/1 or /cosmeticsproducts/1.json
  def update
    respond_to do |format|
      if @cosmeticsproduct.update(cosmeticsproduct_params)
        format.html { redirect_to cosmeticsproduct_url(@cosmeticsproduct), notice: "Cosmeticsproduct was successfully updated." }
        format.json { render :show, status: :ok, location: @cosmeticsproduct }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cosmeticsproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cosmeticsproducts/1 or /cosmeticsproducts/1.json
  def destroy
    @cosmeticsproduct.destroy

    respond_to do |format|
      format.html { redirect_to cosmeticsproducts_url, notice: "Cosmeticsproduct was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cosmeticsproduct
      @cosmeticsproduct = Cosmeticsproduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cosmeticsproduct_params
      params.require(:cosmeticsproduct).permit(:name, :image, :price, :category)
    end
end

app/helpers/cosmeticsproducts_helper.rb
module CosmeticsproductsHelper
end

app/views/cosmeticsproducts/_cosmeticsproduct.html.erb
<div id="<%= dom_id cosmeticsproduct %>">
  <p>
    <strong>Name:</strong>
    <%= cosmeticsproduct.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= cosmeticsproduct.image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= cosmeticsproduct.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= cosmeticsproduct.category %>
  </p>

</div>

app/views/cosmeticsproducts/_form.html.erb
<%= form_with(model: cosmeticsproduct) do |form| %>
  <% if cosmeticsproduct.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cosmeticsproduct.errors.count, "error") %> prohibited this cosmeticsproduct from being saved:</h2>

      <ul>
        <% cosmeticsproduct.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cosmeticsproducts/edit.html.erb
<h1>Editing cosmeticsproduct</h1>

<%= render "form", cosmeticsproduct: @cosmeticsproduct %>

<br>

<div>
  <%= link_to "Show this cosmeticsproduct", @cosmeticsproduct %> |
  <%= link_to "Back to cosmeticsproducts", cosmeticsproducts_path %>
</div>

app/views/cosmeticsproducts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cosmeticsproducts</h1>

<div id="cosmeticsproducts">
  <% @cosmeticsproducts.each do |cosmeticsproduct| %>
    <%= render cosmeticsproduct %>
    <p>
      <%= link_to "Show this cosmeticsproduct", cosmeticsproduct %>
    </p>
  <% end %>
</div>

<%= link_to "New cosmeticsproduct", new_cosmeticsproduct_path %>

app/views/cosmeticsproducts/new.html.erb
<h1>New cosmeticsproduct</h1>

<%= render "form", cosmeticsproduct: @cosmeticsproduct %>

<br>

<div>
  <%= link_to "Back to cosmeticsproducts", cosmeticsproducts_path %>
</div>

app/views/cosmeticsproducts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cosmeticsproduct %>

<div>
  <%= link_to "Edit this cosmeticsproduct", edit_cosmeticsproduct_path(@cosmeticsproduct) %> |
  <%= link_to "Back to cosmeticsproducts", cosmeticsproducts_path %>

  <%= button_to "Destroy this cosmeticsproduct", @cosmeticsproduct, method: :delete %>
</div>